// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJLTG9jMpmfPGvT8agSMlf3eS-6JapdHk',
    appId: '1:1071055611755:web:f0c0df227da6b320d0ce2e',
    messagingSenderId: '1071055611755',
    projectId: 'servito-services',
    authDomain: 'servito-services.firebaseapp.com',
    storageBucket: 'servito-services.appspot.com',
    measurementId: 'G-HSC6W5JBW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCuB6bKJiuURUNcP9DjwFWfhktYCT3vtU',
    appId: '1:1071055611755:android:df0d336fcd85ce6ad0ce2e',
    messagingSenderId: '1071055611755',
    projectId: 'servito-services',
    storageBucket: 'servito-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MS9vpvm8Ai_XRmNJSYU0kXfFuq7VJO8',
    appId: '1:1071055611755:ios:2605427a359a3109d0ce2e',
    messagingSenderId: '1071055611755',
    projectId: 'servito-services',
    storageBucket: 'servito-services.appspot.com',
    androidClientId: '1071055611755-0i5h7j56gf46f6kf5lskqfe3llpfu61b.apps.googleusercontent.com',
    iosClientId: '1071055611755-f19t1rm2se6liropj4hnti8fv7gp6d5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_MS9vpvm8Ai_XRmNJSYU0kXfFuq7VJO8',
    appId: '1:1071055611755:ios:921503ccd442b57ed0ce2e',
    messagingSenderId: '1071055611755',
    projectId: 'servito-services',
    storageBucket: 'servito-services.appspot.com',
    androidClientId: '1071055611755-0i5h7j56gf46f6kf5lskqfe3llpfu61b.apps.googleusercontent.com',
    iosClientId: '1071055611755-51q4gcfibi6h5qdl2hpubgrq07c521j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fflutter.RunnerTests',
  );
}
